//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCBackend
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class LoadRequest
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public string ProdId { get; set; }
        public double Price { get; set; }
        public System.DateTime SaleDate { get; set; }
        public string State { get; private set; }
        public int LoadResult { get; private set; }
        public Nullable<System.DateTime> DateInitial { get; set; }
    }
}
