//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class PBKey
    {
        public int Id { get; set; }
        public string Algo { get; set; }
        public int HashSize { get; set; }
        public int Cicles { get; set; }
        public string B64Salt { get; set; }
        public string B64Key { private get; set; }
    }
}
