//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCardToken
    {
        public int Id { get; set; }
        public string Data { get; set; }
        public int AccountId { get; set; }
        public System.DateTime DateInitial { get; set; }
        public System.DateTime DateFinal { get; set; }
        public Nullable<double> Amount { get; set; }
        public bool Used { get; set; }
    
        public virtual LoadRequest LoadRequest { get; set; }
    }
}
