//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCard
    {
        public int Id { get; set; }
        public int TokenizedId { get; set; }
        public string Data { get; set; }
    
        public virtual Online OnlineAccount { get; set; }
        public virtual Tokenized TokenizedAccount { get; set; }
    }
}
